### ISSUE TITLE
Responsive map

### ISSUE THREAD

**Issue by goncalosilva** [FacetWP/facetwp-map-facet#12]
Currently, in the map facet, we set width and height but the "older" approach of Facetwp map looks better because it resizes the map according to the available size.
Please consider improving this feature.

**Comment by mgibbs189** [comment]
Possible solution:

```js
google.maps.event.addDomListener(window, "resize", function() {
    var center = map.getCenter();
    google.maps.event.trigger(map, "resize");
    map.setCenter(center);
});
```
