### ISSUE TITLE
Not working with FacetWP 3.0.8

### ISSUE THREAD

**Issue by agileware-fj** [FacetWP/facetwp-map-facet#16]
After upgrade to FacetWP 3.0.8, the map facet appears to be storing a hash in the latitude (value) field (At least with negative latitudes; I haven't tested with northern hemisphere locations)

This causes various issues, including zero latitudes (stored value starting with letters) and invalid bounds (stored value starting with an integer >= 90 and a non-zero longitude).  In the best case, the marker latitude is simply wrong.

No sure exactly where this is happening as debugging suggests immediately before the insert is called it's still the latitude value itself.

**Comment by mgibbs189** [comment]
@agileware-fj what is the facet's Data Source?

**Comment by agileware-fj** [comment]
@mgibbs Data source is an ACF "Google map" field on a custom post type

**Comment by mgibbs189** [comment]
Within the `Data source` dropdown, did you select the field under the "Advanced Custom Fields" header? Or the one under the "Custom Fields" header?

If the latter, change to the former and re-index :)

**Comment by agileware-fj** [comment]
"Advanced Custom Fields"

**Comment by mgibbs189** [comment]
Could you please open a [support ticket](https://facetwp.com/support/)? We're probably going to need to look into your site in more depth.

**Comment by dougkeeling** [comment]
I seem to be having the same issue with version 3.2.6.  The Google map does not load at all, with the correct data source selected as you mentioned above @mgibbs189.
