### ISSUE TITLE
Add ability to disable fitBounds() -- manual center / zoom

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-map-facet#21]
See Help Scout #9738

**Comment by pabowles** [comment]
Any idea when this might be included?

**Comment by mgibbs189** [comment]
@pabowles It's probably a few versions away. Our next priority is on switching the add-on to using Leaflet, thus reducing dependence on Google.

**Comment by pabowles** [comment]
@mgibbs189  Ok thanks for the quick response! Couple of months away then?

**Comment by mgibbs189** [comment]
@pabowles it could be, yes

**Comment by melesch** [comment]
@mgibbs189  Hi, are there any possibilities now to switch the map to leaflet?
