### ISSUE TITLE
Custom Styles

### ISSUE THREAD

**Issue by zestjosh** [FacetWP/facetwp-map-facet#23]
Possible to allow custom styles? I'd like to paste in my own code from snazzymaps.

**Comment by mgibbs189** [comment]
Use this hook: https://d.pr/i/rZ7N0H

**Comment by lincolnlemos** [comment]
Just a remenber for next people:
If you are using JSON from mapstyle.withgoogle.com, use json_decode.

Ex: `$args['init']['styles'] = json_decode(YOUR_COPIED_JSON);`
