### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method FacetWP_Facet_Map_Addon::admin_scripts() 

### ISSUE THREAD

**Issue by olliekav** [FacetWP/facetwp-map-facet#24]
Wordpress: Version 4.9.8
FacetWP: Version 3.0.3
FacetWP - Map Facet: Version 0.4.4

`Fatal error: Uncaught Error: Call to undefined method FacetWP_Facet_Map_Addon::admin_scripts() in /Users/olliekav/Sites/businessforgood/wp-content/plugins/facetwp/templates/page-settings.php on line 43`

The plugin throws the error above on the FacetWP settings page with the latest versions.

**Comment by mgibbs189** [comment]
@olliekav The latest version of FacetWP is 3.2.8..

**Comment by olliekav** [comment]
@mgibbs189 Apologies, my upgrades seemed to have been frozen so I was getting notified. All working now :)
