### ISSUE TITLE
Facetwp Map Not Loading 

### ISSUE THREAD

**Issue by ahsanlt** [FacetWP/facetwp-map-facet#27]
Hey, 
FacetWP Version 3.3.9
FacetWP Map 0.5.1

I created a comma separated text field in ACF after that i set that field as the data source for facetwp map. I have also created a valid google api key.
But map is not showing. Any idea why?

**Comment by mgibbs189** [comment]
Please open a [support ticket](https://facetwp.com/documentation/support/). This isn't the place for support questions.
