### ISSUE TITLE
doubled locations

### ISSUE THREAD

**Issue by webmazing** [FacetWP/facetwp-map-facet#7]
All the locations on the map are doubled.

**Comment by mgibbs189** [comment]
Can you confirm this still happens with the latest code (pulled directly from github)?

**Comment by webmazing** [comment]
This isn't happening anymore. But is there any way to put them further from each other? more space between the markers?

**Comment by mgibbs189** [comment]
I don't see an option for that, unfortunately. The closest thing I see right now is a `spiderWeight` properly which controls the line thickness (not length):

https://github.com/jawj/OverlappingMarkerSpiderfier

Maybe I'm missing it though?
