### ISSUE TITLE
Can't use map filters

### ISSUE THREAD

**Issue by webmazing** [FacetWP/facetwp-map-facet#8]
Can't use map filters to edit markers.

**Comment by mgibbs189** [comment]
Markers aren't editable. I'm not sure why they should be..?

**Comment by webmazing** [comment]
Sorry, not very well described. The filter facetwo_map_marker_args doesn't work anymore. We have put it in a separate plugin:

add_filter( 'facetwp_map_marker_args', function( $args, $post_id ) {
	if( has_term( '3', 'praktijk_cats', $post_id ) ) {
    $args['icon'] = '/assets/img/MapPin_Blauw.png';
    } elseif( has_term( '2', 'praktijk_cats', $post_id ) ) {
	$args['icon'] = '/assets/img/MapPin_Rood.png';   
	} elseif( has_term( '4', 'praktijk_cats', $post_id ) ) {
	$args['icon'] = '/assets/img/MapPin_Oranje.png';  
	} elseif( has_term( '6', 'praktijk_cats', $post_id ) ) {
	$args['icon'] = '/assets/img/MapPin_Grijs.png';  
	} elseif( has_term( '123', 'soort_praktijk', $post_id ) ) {
	$args['icon'] = '/assets/img/MapPin_Rood.png'; 
	} elseif( has_term( '122', 'soort_praktijk', $post_id ) ) {
	$args['icon'] = '/assets/img/MapPin_Blauw.png'; 
	} else { // De rest
	$args['icon'] = '/assets/img/MapPin_Grijs.png';     
	}
    return $args;
}, 10, 2 );

With the "old" plugin this works. With the new map facet we can't use this anymore. We added a icon directly in the front.js (not the right way but it works for now) so we changed the default icon, but we want to change it depending on the custom taxonomy.

**Comment by webmazing** [comment]
Can you reopen this again? Thanks

**Comment by mgibbs189** [comment]
Fixed via 8811ff5
